Document: swapspace
Title: Debian swapspace Manual
Author: <insert document author here>
Abstract: This manual describes what swapspace is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/swapspace/swapspace.sgml.gz

Format: postscript
Files: /usr/share/doc/swapspace/swapspace.ps.gz

Format: text
Files: /usr/share/doc/swapspace/swapspace.text.gz

Format: HTML
Index: /usr/share/doc/swapspace/html/index.html
Files: /usr/share/doc/swapspace/html/*.html
