#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/swapspace" ]; then
	update-rc.d swapspace defaults >/dev/null
	invoke-rc.d swapspace start || exit $?
fi
# End automatically added section
